# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=260)),
                ('bio', models.CharField(max_length=260)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profilepics/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('pub_date',)},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='poster',
            new_name='profile',
        ),
    ]
