# Generated by Django 2.2.3 on 2019-07-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_user_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Uzer',
        ),
    ]
